### PR TITLE
Add ⌘ + Enter keycommand

### LINKED ISSUE #1: ⌘+Enter should invoke send action
Have to manually invoke a send action now. Can’t use an external keyboard’s ⌘+Enter.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

### PR DESCRIPTION
**Pull request by BasThomas**
Fixes #1.

Didn't want to "[all out](https://github.com/slackhq/SlackTextViewController/blob/ac17d975c0e24960657720e505732993aac2257e/Source/SLKTextView.m#L958)" like SlackTV atm; let me know what you think.

### CODE REVIEW

**Comment by rnystrom** [comment]
Awesome!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
@BasThomas GitHawk is just about pulling the remote repos. Quick question, does this disable using the return key on iOS? We still want to be able to enter newlines.

**Comment by BasThomas** [comment]
> does this disable using the return key on iOS?

No; we need the ⌘ Modifier key for it to trigger.

> Also any interest setting up some unit tests for this?
I'll take a look!

**Comment by rnystrom** [comment]
Tests aren’t a big deal, lmk I can merge this now and revisit tests later!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Go ahead!

**Pull request merged**
